BOLD="\e[1m"
DIM="\e[2m"
ITALIC="\e[3m"
UNDERLINE="\e[4m"
DOUBLE_UNDERLINE="\e[21m"
CURLY_UNDERLINE="\e[4:3m"
BLINK="\e[5m"
REVERSE="\e[7m"
HIDDEN="\e[8m"
STRIKETHROUGH="\e[9m"

RESET="\e[0m"
TEXT="Hello world"

echo "Normal:        ${RESET}${TEXT}"
echo "Bold:          ${BOLD}${TEXT}${RESET}"
echo "Italic:        ${ITALIC}${TEXT}${RESET}"
echo "Both:          ${BOLD}${ITALIC}${TEXT}${RESET}"
echo "Dim:           ${DIM}${TEXT}${RESET}"
echo "Underline:     ${UNDERLINE}${TEXT}${RESET}"
echo "Double U-line: ${DOUBLE_UNDERLINE}${TEXT}${RESET}"
echo "Curly U-line:  ${CURLY_UNDERLINE}${TEXT}${RESET}"
echo "Blink:         ${BLINK}${TEXT}${RESET}"
echo "Strikethrough: ${STRIKETHROUGH}${TEXT}${RESET}"
echo "Reverse:       ${REVERSE}${TEXT}${RESET}"
echo "Hidden:        ${HIDDEN}${TEXT}${RESET}"
