name: CI

on:
  push:
    paths-ignore:
      - "**.md"

jobs:
  build:
    name: Build Docker images
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase
        uses: actions/checkout@v2

      - name: Build Arch image
        run: docker build -t jkavan/dotfiles:arch -f=Dockerfile.arch .

      - name: Build Debian latest image
        run: docker build -t jkavan/dotfiles:debian -f=Dockerfile .

      - name: Build Debian Buster image
        run: docker build -t jkavan/dotfiles:debian10 -f=Dockerfile.buster .
